### ISSUE TITLE
[BUG] - PVP module isn't working right.

### ISSUE THREAD

**Issue by biship** [Aldori15/azerothcore-eluna-accountwide#13]
2025-11-04 08:39:13 Unhandled MySQL errno 1264. Unexpected behaviour possible.
2025-11-04 08:39:13 [1264] Out of range value for column 'todayKills' at row 267

Firstly, it's including all rndbots, i don't know if that's intentional, it's not configurable.

<img width="911" height="528" alt="Image" src="https://github.com/user-attachments/assets/91324f06-6a30-44d7-a8b5-d21ea8138c27" />

I set these to zero in the character table just a few days ago when I first noticed this.

I see you using GetUInt32 in the LUA, but some db fields are SMALLINT. 

There must be a logic flaw in the summation of the kills. This is not a PVP server, most bots are level 20-29 and I doubt PVP occurs at all, however the counts are huge.

<img width="965" height="296" alt="Image" src="https://github.com/user-attachments/assets/c55335b0-7885-4278-88f7-8c2e2fd43716" />

The bots havent even logged in today and there are 'todaykills'.

**Comment by Aldori15** [comment]
@biship Hmm.  All of my Accountwide scripts should exclude Rndbots, so that is not intentional.  I must have missed a check somewhere for skipping rndbots so i'll take a look at this.

In the meantime, can you go ahead and set this script to False to turn it off and then can you right click on the `accountwide_pvp_rank` table in HeidiSQL and click Empty Table?  

<img width="482" height="162" alt="Image" src="https://github.com/user-attachments/assets/f915fa2a-b193-4683-a100-d883c112ac96" />

That way the table is emptied for when I submit the fix and it doesn't try to utilize the incorrect data anymore.  Either way, once I find the missing Rndbot exclusion, that should fix itself anyway.

**Comment by biship** [comment]
Thanks, will check when home. Isn't there still a problem with the data type and math?

**Comment by biship** [comment]
Ok, sounds right that my 2k+ rndbots all summed up to those huge numbers. I've updated and will report back if I see anything odd, thanks!

**Comment by Aldori15** [comment]
I'm not seeing that issue with it still creating the rows for Rndbot accounts with the latest changes.  At least for me it is working correctly with not creating rows for Rndbot accounts or pulling in data for them.

**Just to confirm:**
- Inside HeidiSQL, you right clicked the `accountwide_pvp_rank` table and clicked "Empty table(s)"?  So that way the table had 0 rows in it.
- Then you are using the latest script only after emptying the table first?

For me, I emptied the table so it had 0 rows with the server shutdown, then applied the new script and restarted the server.  It only created 3 rows for accounts 102,127,128 which are 3 real player accounts.  None of the Rndbot accounts are showing up.

<img width="1569" height="423" alt="Image" src="https://github.com/user-attachments/assets/c00e1b19-71ae-4c8f-8dd5-4b12d8092c6e" />

<img width="334" height="1181" alt="Image" src="https://github.com/user-attachments/assets/28a0d8c7-ae34-4973-be10-9710beaadce1" />

<img width="325" height="1183" alt="Image" src="https://github.com/user-attachments/assets/4b8bb25d-8e8d-4c3a-b920-87c9ac79e56c" />

**Comment by Aldori15** [comment]
Yeah so here's the issue from what I can tell. We're essentially checking the acore_playerbots.playerbots_account_type table to see if an Account exists in there, and if it does, it's considered an Rndbot since only Rndbots are put in there.

When the # of bots gets increased, the server has to create those accounts as the server starts up, which means those accounts have to get added to that table by the server. 

I'm assuming it's an order of operations thing where they aren't inserted into that table quick enough for my script to realize the new accounts are in there.

To further that theory even more, I would assume that if you then shutdown the server and restart it without changing the # of bots, the previously increased/new bots would then be working as expected since they now exist in that table. I'm pretty sure the issue would only be the first time as they aren't in the table at the time.

I'm not really sure how to combat this. Would really have to think about it, but due to order of operations I'm not sure. Do you have any ideas?

**Comment by Aldori15** [comment]
The easiest way to avoid altogether is if the # of bots get increased while the server is shutdown, turn off all of the scripts, load up the server so it can insert them into the table and then turn the scripts back on after.  That's the easiest way without needing to make any changes.

Not at my PC right now but would maybe need to sit and brainstorm ways around it via code. Adding the delay that you mentioned was my first thought as well but I think it would negatively affect all of the other scripts in ways that we don't want to happen
